plugins:
  # https://github.com/jest-community/eslint-plugin-jest
  - jest
parser: babel-eslint
env:
  node: true
  jest: true
extends:
  - airbnb-base
  - 'plugin:jest/recommended'
rules:
  no-console: 0
